# building.yml
name: Building Docker

# Allow repository modyfication;
permissions:
  contents: write
  packages: write

on:
  # Allow to re-use this jobs;
  #workflow_call:
  #  secrets:
  #    token:
  #      required: false 
  #  inputs:
  #    context:
  #      type: string
  #    file:
  #      type: string

  # Trigger on each tag-push;
  push:
    tags:
      - '*'

  ## Triger manualy;
  #workflow_dispatch:

jobs:

  # -----------------
  # Hadolint 
  # -----------------
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: utilizable/github-actions/.github/actions/linting/docker/hadolint@develop
        with:
          file: ./Dockerfile 

  # -----------------
  # Building & Pushing to Github registry 
  # -----------------
  github:
    needs: [ hadolint ]
    runs-on: ubuntu-latest
    steps:
      - uses: utilizable/github-actions/.github/actions/building/docker/github@develop
        with:
          token: ${{ secrets.token }}
          context: ./ 
          file: ./Dockerfile 
