name: ref 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;
  push:
    branches:
      - '*' 
  # Trigger manually;
  workflow_dispatch:

jobs:
  tagging:
    uses: "${{ GH_ACTIONS }}/tagging.yml@develop"
    secrets:
      PAT: ${{ secrets.PAT }}
