name: ref 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;
  push:
    branches:
      - '*' 
  # Trigger manually;
  workflow_dispatch:

jobs:
  tagging:
    #    uses: "${{ GH_ACTIONS }}/tagging/tagging.yml@develop"
    uses: "utilizable/github-actions/.github/workflows/tagging/tagging.yml"
    secrets:
      PAT: ${{ secrets.PAT }}
