name: semver 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;
  push:
    branches:
      - '*' 

  # Trigger manually;
  workflow_dispatch:

jobs:
  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/semver.yml@develop
    secrets:
      PAT: ${{ secrets.PAT }}
