name: tag 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;  
  push:
    tags:
      - '*' 

  # Trigger manually;
  workflow_dispatch:

jobs:
  build:
    uses: utilizable/github-actions/.github/workflows/building_docker.yml@develop
    secrets:
      PAT: ${{ secrets.PAT }}
    with:
      context: ./
