name: workflow 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;  
  push:
  # Trigger manually;
  workflow_dispatch:

jobs:

# -----------------
# SEMVER 
# -----------------

  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/tagging.yml@feat/output

# -----------------
# DOCKER BUILDING
# -----------------
      
  # DOCKER BUILDING
  build:
    needs: semver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Build and Push
        uses: utilizable/github-actions-docker-building/.github/workflows/building.yml@develop
        with:
          tag: ${{ needs.semver.outputs.tag }}
