name: workflow 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;  
  push:
  # Trigger manually;
  workflow_dispatch:

jobs:

# -----------------
# SEMVER 
# -----------------

  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/tagging.yml@feat/output

# -----------------
# DOCKER BUILDING
# -----------------
  build:
    runs-on: ubuntu-latest
    needs: semver
    steps:
      - run: echo ${{ needs.semver.outputs.tag }}

      - name: Build step
        run: |
          echo "Building with tag ${{ needs.semver.outputs.tag }}"
          
  #building:
  #  needs: semver
  #  uses: utilizable/github-actions-docker-building/.github/workflows/building.yml@develop
  #  with:
  #    tag: ${{ needs.semver.outputs.tag }}
