name: CI Workflow

# Allow repository modification
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automatically for semver job
  push:

  # Trigger manually
  workflow_dispatch:

jobs:
  semver:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
    uses: utilizable/github-actions-semver-tagging/.github/workflows/semver.yml@develop
    secrets:
      PAT: ${{ secrets.PAT }}

  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: utilizable/github-actions-docker-building/.github/workflows/building.yml@develop
