name: workflow 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;  
  push:
  # Trigger manually;
  workflow_dispatch:

jobs:

# -----------------
# SEMVER 
# -----------------

  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/semver.yml@develop
    secrets:
      PAT: ${{ secrets.PAT }}
      
# -----------------
# DOCKER BUILDING
# -----------------
      
  build:
#    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    uses: utilizable/github-actions-docker-building/.github/workflows/building.yml@develop
